---
controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - front_left_wheel_connection_link_joint
      - front_right_wheel_connection_link_joint
      - back_left_wheel_connection_link_joint
      - back_right_wheel_connection_link_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

forward_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_link_joint
      - front_right_wheel_link_joint
      - back_left_wheel_link_joint
      - back_right_wheel_link_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
